"use client";

import { useEffect, useState } from "react";
import { FaArrowRightArrowLeft, FaCreditCard, FaShieldHalved, FaWallet } from "react-icons/fa6";
import { FiActivity, FiTrendingUp } from "react-icons/fi";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { Language } from "@/components/LandingPage";

type DailyPoint = { date: string; count: number };
type Stats = { start_date: string; end_date: string; acquisition: { registered_users: number; avg_per_day: number; avg_per_week: number; avg_per_month: number; series_daily: DailyPoint[] }; active_users: { definition: string; avg_per_day: number; avg_per_week: number; avg_per_month: number; series_daily: DailyPoint[] }; kyc: { approved: number; approved_with_sudo_account: number; refused: number; not_done: number; pending: number }; accounts: { xof: number; ngn: number; inactive: number; deleted: number }; cards: { created: number; active: number; blocked: number }; transactions: { xof: { count: number; volume: number }; ngn: { count: number; volume: number }; series_daily: { date: string; xof: number; ngn: number }[] } };
type Period = "month" | "quarter" | "year" | "all";
type ActiveUsersMode = "all" | "login" | "transaction";
type ChartLine = { key: string; label: string; color: string };

const content = {
  fr: { title: "Statistiques commerciales", loading: "Chargement des données…", updating: "Mise à jour des statistiques…", error: "Impossible de charger les statistiques.", empty: "Aucune donnée sur cette période.", to: "au", clear: "Effacer", periods: { month: "Mois", quarter: "Trimestre", year: "Année", all: "Tout" }, activeModes: { all: "Tous", login: "Connexion", transaction: "Transaction" }, definitions: { login: "Connexion", transaction: "Transaction", login_or_transaction: "Tous" }, acquisition: "Acquisition", activeUsers: "Utilisateurs actifs", kyc: "KYC", accounts: "Comptes", cards: "Cartes", transactions: "Transactions (complétées, période)", registered: "Inscrits (total)", daily: "Moyenne / jour", weekly: "Moyenne / semaine", monthly: "Moyenne / mois", registrations: "Inscriptions par jour", signups: "Inscriptions", activeDaily: "Utilisateurs actifs par jour", users: "Utilisateurs", approved: "Approuvés", sudo: "Approuvés + compte Sudo Naira", refused: "Refusés", notDone: "Non fait", pending: "En attente", xofAccounts: "Comptes XOF", ngnAccounts: "Comptes NGN", inactive: "Comptes inactifs", deleted: "Comptes supprimés", created: "Cartes créées", active: "Cartes actives", blocked: "Cartes bloquées", xofTransactions: "Transactions XOF", ngnTransactions: "Transactions NGN", volume: "Volume", transactionVolume: "Volume des transactions complétées", startDate: "Date de début", endDate: "Date de fin", periodLabel: "Période statistiques" },
  en: { title: "Commercial statistics", loading: "Loading data…", updating: "Updating statistics…", error: "Unable to load statistics.", empty: "No data for this period.", to: "to", clear: "Clear", periods: { month: "This month", quarter: "Quarter", year: "Year", all: "All time" }, activeModes: { all: "All", login: "Login", transaction: "Transaction" }, definitions: { login: "Login", transaction: "Transaction", login_or_transaction: "All" }, acquisition: "Acquisition", activeUsers: "Active users", kyc: "KYC", accounts: "Accounts", cards: "Cards", transactions: "Transactions (completed, period)", registered: "Registered users", daily: "Average / day", weekly: "Average / week", monthly: "Average / month", registrations: "Daily registrations", signups: "Registrations", activeDaily: "Daily active users", users: "Users", approved: "Approved", sudo: "Approved + Sudo Naira account", refused: "Declined", notDone: "Not completed", pending: "Pending", xofAccounts: "XOF accounts", ngnAccounts: "NGN accounts", inactive: "Inactive accounts", deleted: "Deleted accounts", created: "Cards created", active: "Active cards", blocked: "Blocked cards", xofTransactions: "XOF transactions", ngnTransactions: "NGN transactions", volume: "Volume", transactionVolume: "Completed transaction volume", startDate: "Start date", endDate: "End date", periodLabel: "Statistics period" },
} as const;

function StatCard({ label, value, subtitle }: { label: string; value: string; subtitle?: string }) { return <article className="investor-stat-card"><span>{label}</span><strong>{value}</strong>{subtitle ? <small>{subtitle}</small> : null}</article>; }

function CommercialLineChart({ title, data, lines, currency, empty, formatNumber, formatDate }: { title: string; data: Array<Record<string, string | number>>; lines: ChartLine[]; currency?: boolean; empty: string; formatNumber: (v: number) => string; formatDate: (v: string) => string }) {
  const chartData = data.map((point) => Object.fromEntries(Object.entries(point).map(([key, value]) => [key, key === "date" ? value : Number(value) || 0])));
  return <article className="investor-chart-card"><div className="investor-chart-title"><h3>{title}</h3>{lines.length > 1 ? <div className="investor-chart-legend">{lines.map((line) => <span key={line.key}><i style={{ backgroundColor: line.color }} />{line.label}</span>)}</div> : null}</div>{chartData.length ? <div className="investor-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData} margin={{ left: 4, right: 12, top: 8, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e8eef3" /><XAxis dataKey="date" tickLine={false} axisLine={false} tickMargin={8} minTickGap={32} tickFormatter={(value) => formatDate(String(value))} /><YAxis tickLine={false} axisLine={false} allowDecimals={!currency} width={currency ? 58 : 40} tickFormatter={(value) => formatNumber(Number(value))} /><Tooltip labelFormatter={(value) => formatDate(String(value))} formatter={(value, name) => [`${formatNumber(Number(value))}${currency ? ` ${String(name).toUpperCase()}` : ""}`, lines.find((line) => line.key === String(name))?.label ?? String(name)]} /><Line type="monotone" dataKey={lines[0].key} name={lines[0].key} stroke={lines[0].color} strokeWidth={2} dot={lines.length === 1 ? { r: 3, fill: lines[0].color, strokeWidth: 0 } : false} activeDot={{ r: 5 }} />{lines.slice(1).map((line) => <Line key={line.key} type="monotone" dataKey={line.key} name={line.key} stroke={line.color} strokeWidth={2} dot={false} activeDot={{ r: 5 }} />)}</LineChart></ResponsiveContainer></div> : <p className="investor-empty-chart">{empty}</p>}</article>;
}

export default function InvestorCommercialStats({ language }: { language: Language }) {
  const copy = content[language]; const locale = language === "fr" ? "fr-FR" : "en-GB";
  const formatNumber = (value: number) => new Intl.NumberFormat(locale, { maximumFractionDigits: 2 }).format(Number(value) || 0);
  const formatDate = (value: string) => { const date = new Date(`${value}T12:00:00`); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString(locale, { day: "2-digit", month: "short" }); };
  const [stats, setStats] = useState<Stats | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [period, setPeriod] = useState<Period>("month"); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [activeUsersMode, setActiveUsersMode] = useState<ActiveUsersMode>("all");
  useEffect(() => { const controller = new AbortController(); const params = new URLSearchParams({ period }); if (startDate && endDate) { params.set("start_date", startDate); params.set("end_date", endDate); } if (activeUsersMode !== "all") params.set("active_users_mode", activeUsersMode); setLoading(true); setError(""); fetch(`/api/investors/commercial?${params}`, { cache: "no-store", signal: controller.signal }).then(async (response) => ({ response, result: await response.json() })).then(({ response, result }) => { if (!response.ok || !result.ok) throw new Error(result.error); setStats(result.data as Stats); }).catch((reason) => { if (reason instanceof Error && reason.name === "AbortError") return; setError(reason instanceof Error ? reason.message : copy.error); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [activeUsersMode, copy.error, endDate, period, startDate]);
  const changePeriod = (nextPeriod: Period) => { setPeriod(nextPeriod); setStartDate(""); setEndDate(""); }; const customRangeActive = Boolean(startDate && endDate);
  return <section className="investor-stats"><div className="investor-stats-heading"><div><p className="investor-eyebrow">CASHLESS INVESTORS</p><h1>{copy.title}</h1><p>{stats ? `${stats.start_date} — ${stats.end_date}` : copy.loading}</p></div><div className="investor-filters"><div className="investor-period-buttons" aria-label={copy.periodLabel}>{(["month", "quarter", "year", "all"] as Period[]).map((value) => <button type="button" key={value} className={!customRangeActive && period === value ? "is-active" : ""} onClick={() => changePeriod(value)}>{copy.periods[value]}</button>)}</div><div className="investor-date-range"><input aria-label={copy.startDate} type="date" value={startDate} max={endDate || undefined} onChange={(event) => setStartDate(event.target.value)} /><span>{copy.to}</span><input aria-label={copy.endDate} type="date" value={endDate} min={startDate || undefined} onChange={(event) => setEndDate(event.target.value)} />{customRangeActive ? <button type="button" onClick={() => { setStartDate(""); setEndDate(""); }}>{copy.clear}</button> : null}</div></div></div>{error ? <p className="investor-error" role="alert">{error}</p> : null}{loading && !stats ? <p className="investor-loading">{copy.loading}</p> : null}{stats ? <div className="investor-board-wrap">{loading ? <div className="investor-loading-overlay" role="status"><i />{copy.updating}</div> : null}<div className="investor-board">
    <section className="investor-section"><h2><FiTrendingUp />{copy.acquisition}</h2><div className="investor-stat-grid investor-stat-grid-four"><StatCard label={copy.registered} value={formatNumber(stats.acquisition.registered_users)} /><StatCard label={copy.daily} value={formatNumber(stats.acquisition.avg_per_day)} /><StatCard label={copy.weekly} value={formatNumber(stats.acquisition.avg_per_week)} /><StatCard label={copy.monthly} value={formatNumber(stats.acquisition.avg_per_month)} /></div><CommercialLineChart title={copy.registrations} data={stats.acquisition.series_daily} lines={[{ key: "count", label: copy.signups, color: "#0c9d83" }]} empty={copy.empty} formatNumber={formatNumber} formatDate={formatDate} /></section>
    <section className="investor-section"><div className="investor-section-title"><h2><FiActivity />{copy.activeUsers} <em>({copy.definitions[stats.active_users.definition as keyof typeof copy.definitions] ?? stats.active_users.definition})</em></h2><div className="investor-mode-toggle">{(["all", "login", "transaction"] as ActiveUsersMode[]).map((mode) => <button type="button" key={mode} className={activeUsersMode === mode ? "is-active" : ""} onClick={() => setActiveUsersMode(mode)}>{copy.activeModes[mode]}</button>)}</div></div><div className="investor-stat-grid investor-stat-grid-three"><StatCard label={copy.daily} value={formatNumber(stats.active_users.avg_per_day)} /><StatCard label={copy.weekly} value={formatNumber(stats.active_users.avg_per_week)} /><StatCard label={copy.monthly} value={formatNumber(stats.active_users.avg_per_month)} /></div><CommercialLineChart title={copy.activeDaily} data={stats.active_users.series_daily} lines={[{ key: "count", label: copy.users, color: "#2563eb" }]} empty={copy.empty} formatNumber={formatNumber} formatDate={formatDate} /></section>
    <section className="investor-section"><h2><FaShieldHalved />{copy.kyc}</h2><div className="investor-stat-grid investor-stat-grid-five"><StatCard label={copy.approved} value={formatNumber(stats.kyc.approved)} /><StatCard label={copy.sudo} value={formatNumber(stats.kyc.approved_with_sudo_account)} /><StatCard label={copy.refused} value={formatNumber(stats.kyc.refused)} /><StatCard label={copy.notDone} value={formatNumber(stats.kyc.not_done)} /><StatCard label={copy.pending} value={formatNumber(stats.kyc.pending)} /></div></section>
    <section className="investor-section"><h2><FaWallet />{copy.accounts}</h2><div className="investor-stat-grid investor-stat-grid-four"><StatCard label={copy.xofAccounts} value={formatNumber(stats.accounts.xof)} /><StatCard label={copy.ngnAccounts} value={formatNumber(stats.accounts.ngn)} /><StatCard label={copy.inactive} value={formatNumber(stats.accounts.inactive)} /><StatCard label={copy.deleted} value={formatNumber(stats.accounts.deleted)} /></div></section>
    <section className="investor-section"><h2><FaCreditCard />{copy.cards}</h2><div className="investor-stat-grid investor-stat-grid-three"><StatCard label={copy.created} value={formatNumber(stats.cards.created)} /><StatCard label={copy.active} value={formatNumber(stats.cards.active)} /><StatCard label={copy.blocked} value={formatNumber(stats.cards.blocked)} /></div></section>
    <section className="investor-section"><h2><FaArrowRightArrowLeft />{copy.transactions}</h2><div className="investor-stat-grid investor-stat-grid-two"><StatCard label={copy.xofTransactions} value={formatNumber(stats.transactions.xof.count)} subtitle={`${copy.volume}: ${formatNumber(stats.transactions.xof.volume)} XOF`} /><StatCard label={copy.ngnTransactions} value={formatNumber(stats.transactions.ngn.count)} subtitle={`${copy.volume}: ${formatNumber(stats.transactions.ngn.volume)} NGN`} /></div><CommercialLineChart title={copy.transactionVolume} data={stats.transactions.series_daily} lines={[{ key: "xof", label: "XOF", color: "#7c3aed" }, { key: "ngn", label: "NGN", color: "#ea580c" }]} currency empty={copy.empty} formatNumber={formatNumber} formatDate={formatDate} /></section>
  </div></div> : null}</section>;
}
